
package component;

import chatt.Message;
import chatt.SceneManager;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import javax.swing.JScrollPane;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import org.joda.time.DateTime;

public class BottomSide extends javax.swing.JPanel {

    public BottomSide() {
        initComponents();
        init();
    }
    private void init(){
        //setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_NEVER);
        TxtField.setLineWrap( true );
        TxtField.setWrapStyleWord( true );
        JScrollPane scroll = new JScrollPane();
        scroll.setViewportView(TxtField);
        add(scroll, "w 100%");
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addFileBtn = new javax.swing.JButton();
        sendBtn = new javax.swing.JButton();
        TxtField = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(30, 31, 34));

        addFileBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/addFile.png"))); // NOI18N
        addFileBtn.setBorder(null);
        addFileBtn.setContentAreaFilled(false);
        addFileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFileBtnActionPerformed(evt);
            }
        });

        sendBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/send.png"))); // NOI18N
        sendBtn.setBorder(null);
        sendBtn.setContentAreaFilled(false);
        sendBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendBtnActionPerformed(evt);
            }
        });

        TxtField.setBackground(new java.awt.Color(49, 51, 56));
        TxtField.setColumns(20);
        TxtField.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        TxtField.setForeground(new java.awt.Color(255, 255, 255));
        TxtField.setRows(5);
        TxtField.setCaretColor(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addComponent(TxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(addFileBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sendBtn)
                .addGap(59, 59, 59))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sendBtn)
                            .addComponent(addFileBtn))
                        .addGap(7, 7, 7)))
                .addGap(26, 26, 26))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void sendBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendBtnActionPerformed
        // TODO add your handling code here:
        String messageTxt = TxtField.getText();
        Message message = new Message(SceneManager.name, new DateTime(), Message.types.TX);
        message.setDataAsString(messageTxt);
        SceneManager.SendMessage(message);
        TxtField.setText("");
    }//GEN-LAST:event_sendBtnActionPerformed

    private void addFileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFileBtnActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Choose File Or Image to Send");
        
        if(fileChooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION){
            FileInputStream fileInputStream = null;
            
            try {
                File selectedFile = fileChooser.getSelectedFile();
                fileInputStream = new FileInputStream(selectedFile.getAbsolutePath());
                
                byte[] fileContentBytes = new byte[(int) selectedFile.length()];
                fileInputStream.read(fileContentBytes);
                
                Message message = new Message(SceneManager.name, new DateTime(), Message.types.FL, selectedFile.getName());
                message.setData(fileContentBytes);
                SceneManager.SendMessage(message);
                
            } catch (FileNotFoundException ex) {
                System.out.println("File not found");
            } catch(IOException ex){
                System.out.println("Error reading");
            } 
            finally {
                try {
                    fileInputStream.close();
                } catch (IOException ex) {
                    Logger.getLogger(BottomSide.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_addFileBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea TxtField;
    private javax.swing.JButton addFileBtn;
    private javax.swing.JButton sendBtn;
    // End of variables declaration//GEN-END:variables
}
